services:
  - type: web
    name: openattend-api
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: openattend-db
          property: connectionString

databases:
  - name: openattend-db
    databaseName: openattend
    user: openattend
